### ISSUE TITLE
Two differences between wenet and espnet

### ISSUE THREAD

**Issue by cosmo1995** [mobvoi/wenet#46]
Thank you for your nice work!
I found two differences between wenet and espnet:
1. Layernorm/Batchnorm in conv module
2. Positional Encoding reverse True/False
Are these modifications necessary？

**Comment by placebokkk** [comment]
@whiteshirt0429 Please help explain this.

In my experiments of aishell-1, using batchnorm in the conv module is better than the layernorm. (both coverage speed and were).

**Comment by whiteshirt0429** [comment]
thanks for your feedback. 
1. Layernorm/Batchnorm are both tried in my early experiments, and the decoder results of  layernorm one are a little better, so we use Layernorm instead of  Batchnorm, and the latest  result of layernorm one on aishell test set even can get 4.59. While @placebokkk  gets a different result with me.We still try to compare the difference, also hope you can help us to verify it. 
2. Positional Encoding reverse True/False: reverse param is not used in current code.
